def q1(x1, x2, y, X1, X2, Y):
    print("BATCH GRADIENT DESCENT")
    print(" ")
    w0, w1, w2, cost, w1_list, w2_list = batch_gradient_descent(x1, x2, y)
    print("W0 :", w0)
    print("W1 :", w1)
    print("W2 :", w2)
    print(" ")
    plot2d("cost", "iterations", cost, "Batch-Gradient-Descent")
    print(" ")
    plot3d(cost, w1_list, w2_list, "cost", "w1", "w2", "Batch-Gradient-Descent")
    print(" ")
    pred(w0, w1, w2, X1, X2, Y)
    time.sleep(5)


def q2(x1, x2, y, X1, X2, Y):
    print(" ")
    print(" ")
    print(" ")
    print("MINI BATCH GRADIENT DESCENT")
    print(" ")
    w0, w1, w2, cost, w1_list, w2_list = mini_batch(x1, x2, y)
    print("W0 :", w0)
    print("W1 :", w1)
    print("W2 :", w2)
    print(" ")
    plot2d("cost", "iterations", cost, "Mini-Batch-Gradient-Descent")
    print(" ")
    plot3d(cost, w1_list, w2_list, "cost", "w1", "w2", "Mini-Batch-Gradient-Descent")
    print(" ")
    pred(w0, w1, w2, X1, X2, Y)
    print(" ")
    print(" ")
    print(" ")
    time.sleep(5)
    print("STOCHASTIC GRADIENT DESCENT")
    w0, w1, w2, cost, w1_list, w2_list = stochastic_gradient_descent(x1, x2, y)
    print("W0 :", w0)
    print("W1 :", w1)
    print("W2 :", w2)
    print(" ")
    plot2d("cost", "iterations", cost, "Stochastic-Gradient-Descent")
    print(" ")
    plot3d(cost, w1_list, w2_list, "cost", "w1", "w2", "Stochastic-Gradient-Descent")
    print(" ")
    pred(w0, w1, w2, X1, X2, Y)
    time.sleep(5)
